after_success:
  - bundle exec codeclimate-test-reporter
before_install:
  - gem update bundler rake
branches:
  only:
    - master
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails-stable.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  webhooks:
    on_start: always
    urls:
      - https://buildlight.collectiveidea.com/
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - ruby-head
script: bundle exec rspec --format=documentation
sudo: false
